; This file was auto-generated by drush_make
core = 7.x

api = 2
projects[drupal][version] = "7.22"

; Modules
projects[views_bulk_operations][version] = "3.1"

projects[addressfield][version] = "1.0-beta3"

projects[addthis][version] = "4.0-alpha2"

projects[auto_entitylabel][version] = "1.1"

projects[backup_migrate][version] = "2.4"

projects[better_formats][version] = "1.0-beta1"

projects[ctools][version] = "1.3"

; Libraries
; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
libraries[chosen][download][type] = "git"
libraries[chosen][download][url] = "git://github.com/harvesthq/chosen.git"
libraries[chosen][directory_name] = "chosen"
libraries[chosen][type] = "library"

projects[chosen][version] = "1.0"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
libraries[ckeditor][download][type] = "get"
libraries[ckeditor][download][url] = "http://download.cksource.com/CKEditor/CKEditor/CKEditor%204.1.1/ckeditor_4.1.1_full.tar.gz"
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][type] = "library"

projects[ckeditor][version] = "1.12"

; Modules
projects[commerce][version] = "1.5"

projects[commerce_add_to_cart_confirmation][version] = "1.0-rc2"

projects[commerce_autosku][version] = "1.1"

projects[commerce_backoffice][version] = "1.2"

projects[commerce_cartmessage][version] = "1.0"

projects[commerce_checkout_login][version] = "1.x-dev"

projects[commerce_checkout_pane_payment][version] = "1.0"

projects[commerce_checkout_progress][version] = "1.2"

projects[commerce_coupon][version] = "1.0-beta7"

projects[commerce_coupon_pct][version] = "1.0-beta7"

projects[commerce_couponprodref][version] = "1.0-alpha1"

projects[commerce_credits][version] = "1.x-dev"

projects[commerce_discount][version] = "1.0-alpha1"

projects[commerce_express_checkout][version] = "1.x-dev"

projects[commerce_extra_panes][version] = "1.1"

projects[commerce_extra_price_formatters][version] = "1.1"

projects[commerce_fieldgroup_panes][version] = "1.0"

projects[commerce_option][version] = "1.0-beta2"

projects[commerce_price_savings_formatter][version] = "1.3"

projects[commerce_product_attributes][version] = "1.0-beta3"

projects[commerce_rules_extra][version] = "1.1"

projects[commerce_shipping][version] = "2.0"

projects[commerce_stock][version] = "2.0-alpha4"

projects[commerce_user_profile_pane][version] = "1.0-beta1"

projects[commerce_views_pane][version] = "1.0-beta2"

projects[compact_forms][version] = "1.0"

projects[date][version] = "2.6"

projects[email_registration][version] = "1.1"

projects[entity][version] = "1.0"

projects[entityreference][version] = "1.0"

projects[eva][version] = "1.2"

projects[extlink][version] = "1.12"

projects[features][version] = "2.0-beta2"

projects[field_formatter_settings][version] = "1.0"

projects[field_group][version] = "1.1"

projects[filefield_paths][version] = "1.0-beta3"

; Libraries
; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
libraries[galleria][download][type] = "git"
libraries[galleria][download][url] = "git://github.com/aino/galleria.git"
libraries[galleria][directory_name] = "galleria"
libraries[galleria][type] = "library"


; Modules

projects[galleria][version] = "1.0-beta3"

projects[globalredirect][version] = "1.5"

projects[hierarchical_select][version] = "3.0-alpha5"

projects[imageapi][version] = "1.x-dev"

projects[imce][version] = "1.7"

projects[inline_entity_form][version] = "1.1"

projects[jquery_update][version] = "2.3"

projects[libraries][version] = "2.1"

projects[panels][version] = "3.3"

projects[pathauto][version] = "1.2"

projects[pm_existing_pages][version] = "1.4"

projects[profiler_builder][version] = "1.0-rc4"

projects[quicktabs][version] = "3.4"

projects[rules][version] = "2.3"

projects[stringoverrides][version] = "1.8"

projects[token][version] = "1.5"

projects[total_control][version] = "2.4"

projects[transliteration][version] = "3.1"

projects[views][version] = "3.7"

projects[views_megarow][version] = "1.0"

projects[views_slideshow][version] = "3.0"

projects[webform][version] = "3.18"

; Themes
projects[adaptivetheme][subdir] = "sites/all/themes"
projects[adaptivetheme][version] = "3.1"

projects[shiny][version] = "1.1"

; Libraries
; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
libraries[jquery.cycle][download][type] = ""
libraries[jquery.cycle][download][url] = ""
libraries[jquery.cycle][directory_name] = "jquery.cycle"
libraries[jquery.cycle][type] = "library"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
libraries[superfish][download][type] = ""
libraries[superfish][download][url] = ""
libraries[superfish][directory_name] = "superfish"
libraries[superfish][type] = "library"

