; This file was auto-generated by drush_make
core = 7.x

api = 2
projects[drupal][version] = "7.22"

;profile
projects[daddy_s_deals][type] = "profile"
projects[daddy_s_deals][download][type] = "git"
projects[daddy_s_deals][download][url] = "git@github.com:perceptum/dd_ecommerce_profile.git"
projects[daddy_s_deals][download][branch] = "master"

