; This file was auto-generated by drush_make
core = 7.x

api = 2

projects[drupal][version] = "7.22"

; Modules
projects[views_bulk_operations][version] = "3.1"

projects[addressfield][version] = "1.0-beta3"

projects[auto_entitylabel][version] = "1.1"

projects[backup_migrate][version] = "2.4"

projects[better_formats][version] = "1.0-beta1"

projects[breakpoints][version] = "1.0"

projects[ctools][version] = "1.3"

; Libraries
; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
libraries[chosen][download][type] = "git"
libraries[chosen][download][url] = "git://github.com/harvesthq/chosen.git"
libraries[chosen][directory_name] = "chosen"
libraries[chosen][type] = "library"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
libraries[ckeditor][download][type] = "get"
libraries[ckeditor][download][url] = "http://download.cksource.com/CKEditor/CKEditor/CKEditor%204.1.1/ckeditor_4.1.1_full.tar.gz"
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][type] = "library"

libraries[chosen][download][type] = "get"
libraries[chosen][download][url] = "http://google-api-php-client.googlecode.com/files/google-api-php-client-0.6.0.tar.gz"
libraries[chosen][directory_name] = "google-api-php-client"
libraries[chosen][type] = "library"

;galleria
libraries[chosen][download][type] = "git"
libraries[chosen][download][url] = "https://github.com/aino/galleria.git"
libraries[chosen][directory_name] = "galleria"
libraries[chosen][type] = "library"




; Modules

;adding projects missing


projects[chosen][version] = "1.0"
projects[galleria][version] = "1.0-beta3"
projects[ckeditor][version] = "1.12"
projects[gauth][version]= "7.x-1.2"
projects[commerce_line_item_cart_form][version]= "7.x-1.2"


projects[addthis][version] = "4.0-alpha2"

projects[commerce][version] = "1.5"

projects[commerce_add_to_cart_confirmation][version] = "1.0-rc2"

projects[commerce_autosku][version] = "1.1"

projects[commerce_backoffice][version] = "1.2"

projects[commerce_cartmessage][version] = "1.0"

projects[commerce_checkout_login][version] = "1.x-dev"

projects[commerce_checkout_pane_payment][version] = "1.0"

projects[commerce_checkout_progress][version] = "1.2"

projects[commerce_checkout_redirect][version] = "2.0-beta1"

projects[commerce_coupon][version] = "1.0-beta7"

projects[commerce_coupon_pct][version] = "1.0-beta7"

projects[commerce_couponprodref][version] = "1.0-alpha1"

projects[commerce_credits][version] = "1.x-dev"

projects[commerce_discount][version] = "1.0-alpha1"

projects[commerce_express_checkout][version] = "1.x-dev"

projects[commerce_extra_panes][version] = "1.1"

projects[commerce_extra_price_formatters][version] = "1.1"

projects[commerce_fieldgroup_panes][version] = "1.0"

projects[commerce_option][version] = "1.0-beta2"

projects[commerce_price_savings_formatter][version] = "1.3"

projects[commerce_product_attributes][version] = "1.0-beta3"

projects[commerce_rules_extra][version] = "1.1"

projects[commerce_shipping][version] = "2.0"

projects[commerce_stock][version] = "2.0-alpha4"

projects[commerce_user_profile_pane][version] = "1.0-beta1"

projects[commerce_views_pane][version] = "1.0-beta2"

projects[compact_forms][version] = "1.0"

projects[date][version] = "2.6"

projects[email_registration][version] = "1.1"

projects[entity][version] = "1.0"

projects[entityreference][version] = "1.0"

projects[eva][version] = "1.2"

projects[extlink][version] = "1.12"

projects[features][version] = "2.0-beta2"

projects[field_formatter_settings][version] = "1.0"

projects[field_group][version] = "1.1"

projects[media][version] = "1.3"

projects[filefield_paths][version] = "1.0-beta3"

projects[picture][version] = "1.1"

; Libraries
; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
;libraries[galleria][download][type] = "git"
;libraries[galleria][download][url] = "https://github.com/aino/galleria.git"
;libraries[galleria][directory_name] = "galleria"
;libraries[galleria][type] = "library"
libraries[galleria][download][type] = "get"
libraries[galleria][download][url] = "http://galleria.io/static/galleria-1.2.9.zip"
libraries[galleria][directory_name] = "galleria"
libraries[galleria][type] = "library"

; Modules
projects[globalredirect][version] = "1.5"

projects[hierarchical_select][version] = "3.0-alpha5"

projects[imageapi][version] = "1.x-dev"

projects[imce][version] = "1.7"

projects[inline_entity_form][version] = "1.1"

projects[jquery_update][version] = "2.3"

projects[libraries][version] = "2.1"

projects[overlay_paths][version] = "1.2"

projects[panels][version] = "3.3"

projects[pathauto][version] = "1.2"

projects[pm_existing_pages][version] = "1.4"

projects[quicktabs][version] = "3.4"

projects[rules][version] = "2.3"

projects[stringoverrides][version] = "1.8"

projects[token][version] = "1.5"

projects[total_control][version] = "2.4"

projects[transliteration][version] = "3.1"

projects[views][version] = "3.7"

projects[views_megarow][version] = "1.0"

projects[views_slideshow][version] = "3.0"

projects[webform][version] = "3.18"

; Themes
;projects[adaptivetheme][subdir] = "sites/all/themes"
projects[adaptivetheme][version] = "3.1"

projects[omega][version] = "3.1"

projects[shiny][version] = "1.1"

projects[dd][download][type] = "git"
projects[dd][download][url] = "git@github.com:perceptum/dd_ecommerce_theme.git"
projects[dd][download][subdir] = "sites/all/themes"
projects[dd][type] = "theme"


; Libraries
; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
libraries[flexslider][download][type] = "git"
libraries[flexslider][download][url] = "git://github.com/woothemes/FlexSlider.git"
libraries[flexslider][directory_name] = "flexslider"
libraries[flexslider][type] = "library"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
libraries[jquery.cycle][download][type] = "git"
libraries[jquery.cycle][download][url] = "git://github.com/malsup/cycle.git"
librariey[jquery.cycle][directory_name] = "jquery.cycle"
libraries[jquery.cycle][type] = "library"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
libraries[json2][download][type] = "get"
libraries[json2][download][url] = "https://github.com/douglascrockford/JSON-js/blob/master/json2.js"
libraries[json2][directory_name] = "json2"
libraries[json2][type] = "library"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
libraries[Mobile_Detect][download][type] = "git"
libraries[Mobile_Detect][download][url] = "https://github.com/serbanghita/Mobile-Detect.git"
libraries[Mobile_Detect][directory_name] = "Mobile_Detect"
libraries[Mobile_Detect][type] = "library"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
libraries[superfish][download][type] = "git"
libraries[superfish][download][url] = "https://github.com/mehrpadin/Superfish-for-Drupal.git"
libraries[superfish][directory_name] = "superfish"
libraries[superfish][type] = "library"


;add additional / new libraries here

projects[] = "clientside_validation"
projects[] = "commerce_google_analytics"
projects[] = "commerce_options_stock"
projects[] = "commerce_repair"
projects[] = "delta"
projects[] = "fb"
projects[] = "ga_login"
;projects[] = "image_gallery"
projects[] = "metatag"
;projects[] = "oauth_common"
projects[] = "profiler_builder"
projects[] = "redirect"
projects[] = "resp_img"
projects[] = "strongarm"
projects[] = "superfish"
projects[] = "twitter"
projects[] = "views_load_more"
projects[] = "waypoints"
projects[] = "webform_conditional"
projects[] = "xmlsitemap"
projects[] = "themekey"
projects[] = "omega_tools"
projects[] = "mobile_switch"
projects[] = "mobile_switch_block"
projects[] = "media_youtube"
projects[] = "commerce_message"
projects[] = "services"
projects[] = "jquery_ui_multiselect_widget"



;************ DADDYS DEALS SPECIFIC ********************
projects[dd][download][type] = "git"
projects[dd][download][url] = "git@github.com:perceptum/dd_ecommerce_modules.git"
projects[dd][download][subdir] = "sites/all/modules/dd_contrib"
projects[dd][type] = "module"
